
name: PR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Setup Altipla tools
        run: go install github.com/altipla-consulting/linter@latest

      - name: Lint
        run: make lint

      - name: Test
        run: make test
